# Generated by Django 5.2.9 on 2026-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shares_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео')], default='text', max_length=10, verbose_name='Тип публікації'),
        ),
    ]
