# Generated by Django 5.2.9 on 2026-01-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_like_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='file',
        ),
    ]
