services:
  - type: web
    name: django-daphne-app
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "0"

      - key: SECRET_KEY
        generateValue: true

      - key: ALLOWED_HOSTS
        value: .onrender.com

      - key: REDIS_URL
        fromService:
          type: redis
          name: django-redis
          property: connectionString

databases:
  - name: django-redis
    plan: free
    type: redis