# Generated by Django 5.2.9 on 2026-02-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
        ('auth_system', '0004_alter_profile_options_and_more'),
    ]

    operations = [
    ]
